version: '3.8'

services:
  api:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Uas_pipi_aliya1
      POSTGRES_DB: uas-db
    ports:
      - "5432:5432"
