[project]
name = "edutrack"
version = "0.0.1"
requires-python = ">=3.13,<4.0"
dependencies = [
    "flask>=3.1.1",
    "google-cloud-storage>=3.1.1",
    "werkzeug>=3.1.3",
]

[tool.uv]
package = false
